from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Ellipse, FancyArrowPatch

def save_fig1(path):
    fig, ax = plt.subplots(figsize=(10,4.8)); ax.axis("off")
    xs=[0.05,0.19,0.33,0.47,0.61,0.75,0.89]
    labels=["Input\n1","32","64","128","64","32","Mask\n1"]
    heights=[0.68,0.58,0.48,0.38,0.48,0.58,0.68]
    for x,l,h in zip(xs,labels,heights):
        ax.add_patch(Rectangle((x-0.045,0.5-h/2),0.09,h,fill=False,lw=2)); ax.text(x,0.5,l,ha="center",va="center")
    for a,b in zip(xs[:-1],xs[1:]): ax.add_patch(FancyArrowPatch((a+0.05,0.5),(b-0.05,0.5),arrowstyle="->",mutation_scale=15))
    ax.text(.5,.93,"U-Net encoder-decoder with skip-connected multi-scale feature extraction",ha="center")
    ax.text(.5,.08,"Paper-style architectural schematic generated by the reproduction code",ha="center")
    fig.tight_layout(); fig.savefig(path,dpi=180,bbox_inches="tight"); plt.close(fig)

def save_fig2(path):
    fig, ax=plt.subplots(figsize=(10,3.2)); ax.axis("off")
    labels=["Panoramic\nX-rays + masks","Preprocess\nresize/normalize","Train U-Net","Evaluate\nDice + IoU","Postprocess\ncomponents/contours","Final\nvisual outputs"]
    xs=np.linspace(.08,.92,len(labels))
    for x,l in zip(xs,labels): ax.add_patch(Rectangle((x-.065,.38),.13,.24,fill=False,lw=2)); ax.text(x,.5,l,ha="center",va="center",fontsize=9)
    for a,b in zip(xs[:-1],xs[1:]): ax.annotate("",xy=(b-.07,.5),xytext=(a+.07,.5),arrowprops=dict(arrowstyle="->",lw=1.7))
    ax.set_title("Reimplemented workflow"); fig.tight_layout(); fig.savefig(path,dpi=180,bbox_inches="tight"); plt.close(fig)

def save_fig4(path):
    fig, ax=plt.subplots(figsize=(5,4)); ax.set_aspect("equal"); ax.axis("off")
    ax.add_patch(Ellipse((.43,.52),.55,.48,fill=False,lw=3)); ax.add_patch(Ellipse((.60,.52),.55,.48,fill=False,lw=3,ls="--"))
    ax.text(.26,.79,"Ground truth",ha="center"); ax.text(.77,.79,"Prediction",ha="center"); ax.text(.515,.52,"Intersection",ha="center",va="center"); ax.text(.5,.12,"IoU = intersection / union",ha="center")
    ax.set_xlim(0,1); ax.set_ylim(0,1); fig.tight_layout(); fig.savefig(path,dpi=180,bbox_inches="tight"); plt.close(fig)
